pipeline {
    agent any 
    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/desalab/devops-api-contactos'
            }
        }
        stage('Check install java') {
            steps {
                sh 'java -version'
            }
        }   
        stage('Build') {
            steps {
                sh 'echo “building the app” '
            }
        }
        stage('Test') {
            steps {
                sh 'echo “Running tests” '
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo “deploying” '
            }
        }

    }
    
    post {
        always {
            echo 'Limpiando el espacio de trabajo...'
        }
        success {
            echo 'El despliegue fue exitoso.'
        }
    }
}
