pipeline {
    /* Define dónde se ejecutará el pipeline. 'any' significa cualquier agente disponible */
    agent any 

    stages {
        /* Los stages dividen el proceso en fases lógicas (Build, Test, Deploy) */
        stage('Bienvenida') {
            steps {
                echo '¡Hola Mundo desde Jenkins!'
            }
        }
        // verificar la version de java
        stage('Verificar Java') {
            steps {
                echo 'Verificando la versión de Java instalada...'
                sh 'java -version'
            }
        }
        // compilando el codigo fuente con maven el la carpeta del contactos-api
        stage('Compilar con Maven') {
            steps {
                echo 'Compilando el proyecto con Maven...'
                dir('contactos-api') {
                    sh './mvnw clean install'
                }
            }
        }
        stage('Información del Sistema') {
            steps {
                echo 'Estamos ejecutando este Job en el nodo:'
                // Los comandos de shell se ejecutan con 'sh' en Linux o 'bat' en Windows
                sh 'hostname' 
            }
        }
        stage('Finalización') {
            steps {
                echo 'Pipeline finalizado con éxito.'
            }
        }
    }
    
    /* El bloque post define acciones según el resultado del pipeline */
    post {
        always {
            echo 'Limpiando el espacio de trabajo...'
        }
        success {
            echo 'El despliegue fue exitoso.'
        }
    }
}
